#+TITLE:     Awesome Package Manager
#+AUTHOR:    damon-kwok
#+EMAIL:     damon-kwok@outlook.com
#+DATE:      2018-01-15
#+OPTIONS: toc:nil creator:nil author:nil email:nil timestamp:nil html-postamble:nil
#+TODO: TODO DOING DONE

[[https://www.patreon.com/DamonKwok][https://awesome.re/badge-flat2.svg]]
[[https://orgmode.org/][https://img.shields.io/badge/Made%20with-Orgmode-1f425f.svg]]
[[https://github.com/damon-kwok/awesome-package-manager/blob/master/LICENSE][https://img.shields.io/badge/license-BSD%202%20Clause-2e8b57.svg]]
[[https://www.patreon.com/DamonKwok][https://img.shields.io/badge/Support%20Me-%F0%9F%92%97-ff69b4.svg]]

A list of package manager.

[[https://github.com/damon-kwok/awesome-package-manager][Homepage]]

[[https://imgs.xkcd.com/comics/packages.png]]

** Programming Languages
| Language-I          | Activity                                                                  | Installer          | PackageManager          | PackageViewer               |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| [[https://tiswww.case.edu/php/chet/bash/bashtop.html][Bash]]                | [[https://github.com/bminor/bash][https://img.shields.io/github/last-commit/bminor/bash.svg]]                 | Built-in           | [[https://github.com/bpkg/bpkg][bpkg]]/[[https://github.com/bpm-rocks/bpm][bpm]]/[[https://github.com/basherpm/basher][basher]]/[[https://github.com/hyperupcall/basalt][basalt]]         | [[http://www.bpkg.sh/][bpkg.sh]]                     |
| *[[http://www.open-std.org/JTC1/SC22/WG14/][C]]* ([[http://libcello.org/][libcello]])      | [[https://github.com/gcc-mirror/gcc][https://img.shields.io/github/last-commit/gcc-mirror/gcc.svg]]              | [[https://gcc.gnu.org/][GCC]] [[http://clang.llvm.org/][Clang]]          | [[https://github.com/clibs/clib/wiki/Packages][clib]]                    | [[https://github.com/clibs/clib/wiki/Packages][Packages]]                    |
| [[http://groups.umd.umich.edu/cis/course.des/cis400/cobol/cobol.html][COBOL]] ([[https://github.com/openmainframeproject/cobol-programming-course][course]])      | [[https://github.com/paulsmith/gnucobol][https://img.shields.io/github/last-commit/paulsmith/gnucobol.svg]]          | [[https://open-cobol.sourceforge.io/][GnuCOBOL]] [[https://github.com/opensourcecobol/opensource-cobol][OpenCobol]] | [[https://github.com/Avuxo/Necropolis][Necropolis]]              | [[https://github.com/Avuxo/Necropolis/tree/master/server/packages][Packages]]                    |
| [[http://www.cplusplus.com/][C++]] ([[https://github.com/AnthonyCalandra/modern-cpp-features][Features]])      | /                                                                         | [[https://gcc.gnu.org/][GCC]] [[http://clang.llvm.org/][Clang]] [[https://www.visualstudio.com/downloads/][VS]]       | [[https://github.com/Microsoft/vcpkg][Vcpkg]] / [[https://conan.io/][Conan]]           | [[https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/][Libs]]/[[https://bintray.com/conan][Private]]&[[https://bintray.com/bincrafters/public-conan][Pub]]            |
| [[https://www.fortran.com/][Fortran]]             | /                                                                         | [[http://www.g95.org/][G95]] [[https://software.intel.com/en-us/parallel-studio-xe/choose-download][IFC]] [[http://simplyfortran.com/][S]] [[https://github.com/flang-compiler/f18][F18]] [[https://lfortran.org/][L]]    | [[http://packages.simplyfortran.com/client.html][Simply]]/[[https://fpm.fortran-lang.org/en/index.html][FPM]]              | [[http://packages.simplyfortran.com/search/index.html][SimplyPackages]]/[[https://fortran-lang.org/packages/fpm][FPM Registry]] |
| [[http://prolog.org/][Prolog]]              | /                                                                         | [[http://gprolog.org/#download][GNU]] [[https://www.swi-prolog.org/download][SWI]] [[https://riptutorial.com/prolog][more...]]    | [[https://www.swi-prolog.org/pldoc/doc/_SWI_/library/prolog_pack.pl][pack.pl]] [[https://github.com/wouterbeek/ppm][PPM]]             | [[https://www.swi-prolog.org/pack/list][Pcakages]]                    |
| [[http://www.smalltalk.org/][Smalltalk]]           | /                                                                         | [[http://pharo.org/download][Pharo]]              | [[https://github.com/hernanmd/pi][PI]]                      | [[http://www.smalltalkhub.com/][SmalltalkHub]]                |
| [[http://sml-family.org/Basis/][SML]]                 | [[https://github.com/standardml/smackage][https://img.shields.io/github/last-commit/standardml/smackage.svg]]         | [[http://smlnj.org/][smlnj]]              | [[https://github.com/standardml/smackage][smackage]]                | [[http://sml-family.org/Basis/][SML-Basis-Library]]           |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| *Language-II*       | Activity                                                                  | Installer          | PackageManager          | PackageViewer               |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| [[https://www.adacore.com/][Ada]]                 | /                                                                         | [[https://www.adacore.com/download][GANT]]               | [[https://github.com/alire-project/alire][ALIRE]]                   | [[https://github.com/alire-project/alire-index][AlireCatalog]]                |
| [[https://cmake.org/][CMake]]               | [[https://github.com/Kitware/CMake][https://img.shields.io/github/last-commit/Kitware/CMake.svg]]               | [[https://cmake.org/download][Download]]           | [[https://github.com/iauns/cpm][CPM]]                     | [[http://www.cpm.rocks/][CPMRepository]]               |
| [[https://docs.hunter.sh/en/latest/quick-start.html][CMake (Hunter)]]      | /                                                                         | [[https://docs.hunter.sh/en/latest/quick-start/boost-components.html][Manual]]             | [[https://github.com/ruslo/hunter][Hunter]]                  | [[https://docs.hunter.sh/en/latest/packages.html][HunterPackages]]              |
| [[https://cocoapods.org/][Cocoa]]([[https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html][Objc]]/[[https://swift.org/][Swift]])   | [[https://github.com/CocoaPods/CocoaPods][https://img.shields.io/github/last-commit/CocoaPods/CocoaPods.svg]]         | [[https://swift.org/download/][*nix]]/[[https://swiftforwindows.github.io/][win]]           | [[https://github.com/Carthage/Carthage][Carthage]]/[[https://github.com/CocoaPods/CocoaPods][CocoaPods]]      | git/[[https://cocoapods.org/][CocoaPods]]               |
| [[https://dlang.org/][D]]                   | [[https://github.com/dlang/dmd][https://img.shields.io/github/last-commit/dlang/dmd.svg]]                   | [[https://dlang.org/download.html][Download]]           | [[http://code.dlang.org/][DUB]] (Built-in)          | [[http://code.dlang.org/][DUBPackages]]                 |
| [[https://dotnet.github.io/][dotnet(.Net)]]        | [[https://github.com/dotnet/runtime][https://img.shields.io/github/last-commit/dotnet/runtime.svg]]              | [[https://www.microsoft.com/net/download/linux][Download]]           | [[https://www.nuget.org/][NuGet]]/[[https://github.com/OneGet/oneget][OneGet]]/[[https://github.com/fsprojects/Paket][Paket]]      | [[https://www.nuget.org/][NuGetPackages]]               |
| [[http://www.erlang.org/][Erlang]]              | [[https://github.com/erlang/otp][https://img.shields.io/github/last-commit/erlang/otp.svg]]                  | [[https://github.com/kerl/kerl][kerl]]               | [[https://s3.amazonaws.com/rebar3/rebar3][rebar3]]                  | [[https://hex.pm/][HexRepository]]               |
| *[[https://www.haskell.org/][Haskell]]*           | [[https://github.com/ghc/ghc][https://img.shields.io/github/last-commit/ghc/ghc.svg]]                     | [[http://haskellstack.org][Stack]]              | [[http://haskellstack.org][Stack]]                   | [[https://hackage.haskell.org/][Hackage]]                     |
| [[https://haxe.org/][Haxe]]                | [[https://github.com/HaxeFoundation/haxe/][https://img.shields.io/github/last-commit/HaxeFoundation/haxe.svg]]         | [[https://haxe.org/download/][Download]]           | [[https://lib.haxe.org][haxelib]](Built-in)       | [[https://lib.haxe.org/][HaxeRepository]]              |
| [[https://iolanguage.org/][IO]]                  | [[https://github.com/IoLanguage/io][https://img.shields.io/github/last-commit/IoLanguage/io.svg]]               | [[https://iolanguage.org/binaries.html][Download]]           | /                       | [[https://iolanguage.org/packages.html][Packages]]                    |
| *[[https://www.java.com/][Java]]*              | [[https://github.com/openjdk/jdk][https://img.shields.io/github/last-commit/openjdk/jdk.svg]]                 | [[https://sdkman.io/sdks#java][SDKMAN]] [[https://github.com/openjdk/jdk/tags][Tags]]        | [[http://maven.apache.org/download.cgi][Maven]]/[[https://gradle.org/][Gradle]]            | [[https://mvnrepository.com/][MavenRepository]]             |
| [[https://www.javascript.com/][Javascript]]          | /                                                                         | /                  | [[http://www.jamjs.org/][Jam]]                     | [[http://www.jamjs.org/packages/][Jam Packages]]                |
| [[https://www.latex-project.org/][LaTeX]]               | /                                                                         | [[http://www.tug.org/texlive/][TeX Live]]           | [[https://www.tug.org/texlive/tlmgr.html][tlmgr]]                   | [[https://www.ctan.org/][CTAN]]                        |
| [[https://www.lua.org/][Lua]]                 | [[https://github.com/lua/lua][https://img.shields.io/github/last-commit/lua/lua.svg]]                     | [[https://github.com/mah0x211/lenv][lenv]]               | [[https://github.com/luarocks/luarocks][LuaRocks]]                | [[https://luarocks.org/][luarocks.org]]                |
| *[[https://ocaml.org/][OCaml]]*([[https://github.com/ocaml-multicore/ocaml-multicore][MultiCore]])  | [[https://github.com/ocaml/ocaml][https://img.shields.io/github/last-commit/ocaml/ocaml.svg]]                 | [[https://opam.ocaml.org/][OPAM]]               | [[https://opam.ocaml.org/packages/][OPAM]]                    | [[https://opam.ocaml.org/packages/][OPAMRepository]]              |
| [[http://www.pascal-programming.info/index.php][Pascal]]              | /                                                                         | [[https://www.freepascal.org/][FreePascal]]/[[https://packages.lazarus-ide.org/][Delphi]]  | [[https://wiki.freepascal.org/Online_Package_Manager#Download][OPM]]/[[https://github.com/DelphiPackageManager/DPM][DPM]]                 | [[https://packages.lazarus-ide.org/][Packages]]/[[https://packagecontrol.io/browse][Browse]]             |
| [[https://www.perl.org/][Perl]]                | [[https://github.com/Perl/perl5][https://img.shields.io/github/last-commit/Perl/perl5.svg]]                  | Built-in           | [[https://www.cpan.org/][CPAN]]                    | [[https://www.cpan.org/][CPAN]] [[https://metacpan.org//][meta::cpan]]             |
| [[https://www.python.org/][Python]]([[https://www.pypy.org/][PyPy ]][[https://github.com/pyston/pyston][Pyston]]) | [[https://github.com/python/cpython][https://img.shields.io/github/last-commit/python/cpython.svg]]              | [[https://github.com/pyenv/pyenv][pyenv]]              | [[https://github.com/sdispater/poetry][Poetry]]/[[https://docs.pipenv.org/][Pipenv]]           | [[https://pypi.org][PyPI]]                        |
| [[http://php.net/][PHP]]                 | [[https://github.com/php/php-src][https://img.shields.io/github/last-commit/php/php-src.svg]]                 | [[https://github.com/phpbrew/phpbrew/][phpbrew]]/[[https://github.com/phpenv/phpenv][phpenv]]     | [[https://getcomposer.org][Composer]]/[[http://eirt.science/xpm/][XPM]]            | [[https://packagist.org/][Packagist]]                   |
| [[https://www.qt.io/][QT]]                  | [[https://github.com/qt/qtbase][https://img.shields.io/github/last-commit/qt/qtbase.svg]]                   | [[https://www.qt.io/download][Download]]           | [[https://inqlude.org/get.html][inqlude]]                 | [[https://inqlude.org/][#inqlude]]                    |
| [[https://raku.org/][Raku]] ([[https://raku.guide/][Guide]])        | [[https://github.com/Raku/ecosystem][https://img.shields.io/github/last-commit/Raku/ecosystem.svg]]              | [[https://raku.org/downloads/][Download]]           | [[https://raku.guide/#_raku_modules][zef]] (Built-in)          | [[https://modules.raku.org/][Modules]]                     |
| [[https://www.ruby-lang.org/][Ruby]]                | [[https://github.com/ruby/ruby][https://img.shields.io/github/last-commit/ruby/ruby.svg]]                   | [[https://github.com/rbenv/rbenv][rbenv]]/[[https://github.com/rvm/rvm][rvm]]          | [[https://bundler.io/][Bundler]]                 | [[https://rubygems.org/][Rubygems Repo]]               |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| *Language-III*      | Activity                                                                  | Installer          | PackageManager          | PackageViewer               |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| [[https://wiki.portal.chalmers.se/agda/pmwiki.php][Agda]]                | [[https://github.com/agda/agda][https://img.shields.io/github/last-commit/agda/agda.svg]]                   | [[https://agda.readthedocs.io/en/latest/getting-started/installation.html][INSTALL]]            | /                       | [[https://wiki.portal.chalmers.se/agda/Main/Libraries][Libraries]]                   |
| [[https://bun.sh/][bun]]                 | [[https://github.com/Jarred-Sumner/bun][https://img.shields.io/github/last-commit/Jarred-Sumner/bun.svg]]           | [[https://bun.sh/][INSTALL]]            | /                       | /                           |
| [[https://crystal-lang.org/][Crystal]]             | [[https://github.com/crystal-lang/crystal][https://img.shields.io/github/last-commit/crystal-lang/crystal.svg]]        | [[https://crystal-lang.org/docs/installation/][Download]]           | [[https://github.com/crystal-lang/shards][Shards]]                  | [[https://crystalshards.herokuapp.com/][Crystalshards]]               |
| [[https://www.dartlang.org][Dart]]                | [[https://github.com/dart-lang/language][https://img.shields.io/github/last-commit/dart-lang/language.svg]]          | [[https://www.dartlang.org/install][Download]]           | [[https://www.dartlang.org/tools/pub][Pub]]                     | [[https://pub.dartlang.org/][DarkPackages]]                |
| [[https://elixir-lang.org/install.html][Elixir]]              | [[https://github.com/elixir-lang/elixir][https://img.shields.io/github/last-commit/elixir-lang/elixir.svg]]          | [[https://elixir-lang.org/install.html][Download]]           | [[https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html][Mix]] (Built-in)          | [[https://hex.pm/][HexRepository]]               |
| [[http://elm-lang.org/][Elm]]                 | [[https://github.com/elm/compiler][https://img.shields.io/github/last-commit/elm/compiler.svg]]                | [[https://guide.elm-lang.org/install.html][Download]]           | [[http://elm-lang.org/blog/announce/package-manager][elm-get]]                 | [[http://package.elm-lang.org/][ElmRepository]]               |
| [[https://eta-lang.org/][Eta]]                 | [[https://github.com/eta-lang/dhall-eta][https://img.shields.io/github/last-commit/eta-lang/dhall-eta.svg]]          | [[https://eta-lang.org/docs/user-guides/eta-user-guide/installation/methods][INSTALL]]            | [[https://github.com/typelead/etlas][Etlas]]                   | [[https://github.com/typelead/eta-hackage][EtaHackage]]                  |
| [[https://fsharp.org/][F#]]                  | [[https://github.com/dotnet/fsharp][https://img.shields.io/github/last-commit/dotnet/fsharp.svg]]               | [[https://dotnet.microsoft.com/download][dotnet]]             | [[https://fake.build/][FAKE]]/[[https://fsprojects.github.io/Paket/][Paket]]              | [[https://www.nuget.org/][NuGet]] [[https://www.fuget.org/][fuget.org]]             |
| [[https://github.com/fetlang/fetlang#building][Fetlang]]             | [[https://github.com/fetlang/fetlang][https://img.shields.io/github/last-commit/fetlang/fetlang.svg]]             | [[https://github.com/fetlang/fetlang#building][building]]           | /                       | /                           |
| [[http://www.fstar-lang.org/][FStar]] ([[https://github.com/project-everest][Everest]])     | [[https://github.com/FStarLang/FStar][https://img.shields.io/github/last-commit/FStarLang/FStar.svg]]             | [[http://www.fstar-lang.org/#download][Download]]           | /                       | /                           |
| [[https://github.com/Frege/frege][Frege]] ([[http://www.frege-lang.org/doc/][doc]])         | [[https://github.com/Frege/frege][https://img.shields.io/github/last-commit/Frege/frege.svg]]                 | [[http://get.frege-lang.org/][grt.frege]]          | [[https://hoogle.haskell.org/][Hoogle]] and [[http://maven.apache.org/download.cgi][Maven]]        | [[https://hoogle.haskell.org/][Stackage]][[http://search.maven.org/][Maven]]               |
| *[[https://golang.org/][Go]]* ([[https://go.dev][go.dev]])       | [[https://github.com/golang/go][https://img.shields.io/github/last-commit/golang/go.svg]]                   | [[https://github.com/travis-ci/gimme][gimme]]/[[https://github.com/moovweb/gvm][gvm]]          | [[https://github.com/golang/dep][dep]]/[[https://github.com/golang/vgo][vgo]]/[[https://github.com/kardianos/govendor][govendor]]        | [[https://pkg.go.dev/][GO.DEV]]/[[https://godoc.org/][GoDoc]]                |
| [[http://www.groovy-lang.org/][Groovy]]              | [[https://github.com/apache/groovy][https://img.shields.io/github/last-commit/apache/groovy.svg]]               | [[https://sdkman.io/sdks#groovy][SDKMAN]]             | [[https://docs.gradle.org/current/userguide/groovy_plugin.html][Gradle]](Plugin)          | [[https://mvnrepository.com/][MavenRepository]]             |
| [[https://www.idris-lang.org/][Idris]]               | [[https://github.com/idris-lang/Idris2][https://img.shields.io/github/last-commit/idris-lang/Idris2.svg]]           | [[https://www.idris-lang.org/download/][Cabal/Stack]]        | [[https://www.idris-lang.org/documentation/packages/][idris]] (Built-in)        | [[https://github.com/idris-lang/Idris-dev/wiki/Libraries][Libraries]]                   |
| *[[https://julialang.org/][Julia]]*             | [[https://github.com/JuliaLang/Julia][https://img.shields.io/github/last-commit/JuliaLang/Julia.svg]]             | [[https://julialang.org/downloads/][Download]]           | [[https://pkg.julialang.org/][Pkg]] (Built-in)          | [[https://pkg.julialang.org/][JuliaRepository]]             |
| [[https://kotlinlang.org/][Kotlin]]              | [[https://github.com/jetbrains/kotlin][https://img.shields.io/github/last-commit/jetbrains/kotlin.svg]]            | [[https://sdkman.io/sdks#java][SDKMAN]]             | [[http://maven.apache.org/download.cgi][Maven]]/[[https://gradle.org/][Gradle]]            | [[https://mvnrepository.com/][MavenRepository]]             |
| [[https://nodejs.org/][Nodejs]]              | [[https://github.com/nodejs/node][https://img.shields.io/github/last-commit/nodejs/node.svg]]                 | [[https://github.com/tj/n][n]]/[[https://github.com/creationix/nvm][nvm]]              | [[https://www.npmjs.com/][npm]]/[[https://classic.yarnpkg.com/en/docs/install][yarn]]                | [[https://www.npmjs.com/][NPMRepo]]/[[https://yarnpkg.com/en/packages][YarnRepo]]            |
| [[https://github.com/oilshell/oil][Oil]] Shell           | [[https://github.com/oilshell/oil][https://img.shields.io/github/last-commit/oilshell/oil.svg]]                | /                  | /                       | /                           |
| [[http://www.purescript.org/][PureScript]]          | [[https://github.com/purescript/purescript][https://img.shields.io/github/last-commit/purescript/purescript.svg]]       | [[https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md][NPM]]                | [[https://github.com/purescript/psc-package][psc-package]]             | [[https://github.com/purescript/package-sets/blob/master/packages.json][packages.json]]               |
| [[https://cran.r-project.org/][R]]                   | [[https://github.com/r-lib/rlang][https://img.shields.io/github/last-commit/r-lib/rlang.svg]]                 | [[https://cran.r-project.org/][Download]]           | [[https://www.r-pkg.org][CRAN]] (Built-in)         | [[https://www.r-pkg.org/][METACRAN]]                    |
| [[https://reasonml.github.io/][ReasonML]]            | [[https://github.com/reasonml/reason][https://img.shields.io/github/last-commit/reasonml/reason.svg]]             | [[https://reasonml.github.io/docs/en/installation][install]]            | [[https://esy.sh/][Esy]]                     | [[https://redex.github.io/][Redex]]                       |
| [[http://www.scala-lang.org/][Scala]]               | [[https://github.com/scala/scala][https://img.shields.io/github/last-commit/scala/scala.svg]]                 | [[https://sdkman.io/sdks#scala][SDKMAN]]             | [[http://www.scala-sbt.org/][SBT]]                     | [[https://mvnrepository.com/][MavenRepository]]             |
| [[https://swift.org/getting-started/#using-the-package-manager][Swift]]               | [[https://github.com/apple/swift][https://img.shields.io/github/last-commit/apple/swift.svg]]                 | [[https://github.com/apple/swift-package-manager#installation][spm]]                | [[https://swift.org/getting-started/#using-the-package-manager][swift]]                   | [[https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#dependencies][Reference]]                   |
| [[https://terralang.org/][Terra]]               | [[https://github.com/terralang/terra][https://img.shields.io/github/last-commit/terralang/terra.svg]]             | [[https://github.com/terralang/terra/releases][Download]]           | /                       | /                           |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| *Language-IV*       | Activity                                                                  | Installer          | PackageManager          | PackageViewer               |
|---------------------+---------------------------------------------------------------------------+--------------------+-------------------------+-----------------------------|
| [[https://alda.io/][Alda]]                | [[https://github.com/alda-lang/alda][https://img.shields.io/github/last-commit/alda-lang/alda.svg]]              | [[https://alda.io/install/][INSTALL]]            | /                       | /                           |
| [[https://www.beeflang.org/][Beef]]                | [[https://github.com/beefproject/beef][https://img.shields.io/github/last-commit/beefproject/beef.svg]]            | [[https://www.beeflang.org/#releases][Releases]]           | /                       | /                           |
| [[https://chapel-lang.org/][Chapel]] ([[https://gitter.im/chapel-lang/chapel][GITTER]])     | [[https://github.com/chapel-lang/chapel][https://img.shields.io/github/last-commit/chapel-lang/chapel.svg]]          | [[https://chapel-lang.org/download.html][Download]]           | [[https://chapel-lang.org/docs/tools/mason/mason.html][Mason]]                   | [[https://github.com/chapel-lang/mason-registry][Mason-Registry]]              |
| [[https://github.com/carbon-language/carbon-lang][Carbon]] ([[https://discord.gg/ZjVdShJDAs][Discord]])    | [[https://github.com/carbon-language/carbon-lang][https://img.shields.io/github/last-commit/carbon-language/carbon-lang.svg]] | [[https://github.com/carbon-language/carbon-lang#getting-started][BUILD]]              | /                       | /                           |
| *[[https://github.com/denoland/deno][Deno]]* ([[https://deno.land/manual][Manual]])     | [[https://github.com/denoland/deno][https://img.shields.io/github/last-commit/denoland/deno.svg]]               | [[https://github.com/denoland/deno_install][deno_install]]       | [[https://deno.land/std/manual.md#built-in-deno-utilities--commands][deno]] (Built-in)         | [[https://deno.land/x/][deno.land/x]]                 |
| [[https://github.com/PistonDevelopers/dyon][Dyon]] ([[http://www.piston.rs/dyon-tutorial/][Tutorial]])     | [[https://github.com/PistonDevelopers/dyon][https://img.shields.io/github/last-commit/PistonDevelopers/dyon.svg]]       | [[http://www.piston.rs/dyon-tutorial/getting-started.html][USAGE]]              | /                       | /                           |
| [[https://elv.sh/][Elvish]]              | [[https://github.com/elves/elvish][https://img.shields.io/github/last-commit/elves/elvish.svg]]                | [[https://elv.sh/get/][INSTALL]]            | /                       | /                           |
| *[[https://factorcode.org/][Factor]]* ([[https://concatenative.org/wiki/view/Factor][wiki]])     | [[https://github.com/factor/factor][https://img.shields.io/github/last-commit/factor/factor.svg]]               | [[https://factorcode.org/#Downloads][Download]]           | /                       | [[https://docs.factorcode.org/content/article-vocab-index.html][Vocabularyindex]]             |
| [[https://flix.dev/][Flix]]                | [[https://github.com/flix/flix][https://img.shields.io/github/last-commit/flix/flix.svg]]                   | [[https://github.com/flix/flix/blob/master/docs/BUILD.md][building]]           | /                       | [[https://api.flix.dev/][Libraries]]                   |
| [[https://futhark-lang.org/][Futhark]] ([[https://futhark-book.readthedocs.io/en/latest/][Book]])      | [[https://github.com/diku-dk/futhark][https://img.shields.io/github/last-commit/diku-dk/futhark.svg]]             | [[https://futhark.readthedocs.io/en/latest/installation.html][INSTALL]]            | [[https://futhark-book.readthedocs.io/en/latest/practical-matters.html#package-management][pkg]] (Built-in)          | [[https://futhark-lang.org/pkgs][pkgs]]                        |
| [[https://gleam.run/][Gleam]]               | [[https://github.com/gleam-lang/gleam][https://img.shields.io/github/last-commit/gleam-lang/gleam.svg]]            | [[https://gleam.run/getting-started/#installing-gleam][INSTALL]]            | rebar3 [[https://gleam.run/writing-gleam/creating-a-project/][gleam]] (Built-in) | [[https://hex.pm/][HexRepository]]               |
| [[https://grain-lang.org/][Grain]]               | [[https://github.com/grain-lang/grain][https://img.shields.io/github/last-commit/grain-lang/grain.svg]]            | [[https://grain-lang.org/docs/getting_grain][INSTALL]]            | /                       | /                           |
| [[https://gluon-lang.org/][Gluon]]               | [[https://github.com/gluon-lang/gluon][https://img.shields.io/github/last-commit/gluon-lang/gluon.svg]]            | [[https://github.com/gluon-lang/gluon#install][INSTALL]]            | /                       | /                           |
| [[https://harelang.org/][Hare]]                | [[https://github.com/liudonghua123/hare][https://img.shields.io/github/last-commit/liudonghua123/hare.svg]]          | [[https://github.com/gluon-lang/gluon#install][INSTALL]]            | /                       | /                           |
| [[https://www.hamler-lang.org/][Hamler]] ([[https://github.com/hamler-lang/documentation/][Docs]])       | [[https://github.com/hamler-lang/hamler][https://img.shields.io/github/last-commit/hamler-lang/hamler.svg]]          | [[https://github.com/hamler-lang/hamler#installation][INSTALL]]            | hamler (Built-in)       | /                           |
| [[https://imba.io/][imba]]                | [[https://github.com/imba/imba][https://img.shields.io/github/last-commit/imba/imba.svg]]                   | [[https://imba.io/][INSTALL]]            | npx                     | [[https://www.npmjs.com/][NPMRepo]]/[[https://yarnpkg.com/en/packages][YarnRepo]]            |
| [[https://www.reddit.com/r/Jai/][Jai]] ([[https://www.youtube.com/watch?v=uZgbKrDEzAs][1]]/[[https://github.com/BSVino/JaiPrimer/blob/master/JaiPrimer.md][2]]/[[https://www.dropbox.com/s/ti5tlxlnl239b5r/jai_basics.pdf][3]]/[[https://twitter.com/Jonathan_Blow][4]]/[[https://inductive.no/jai/][5]])     | [[https://github.com/pixeldroid/jailang][https://img.shields.io/github/last-commit/pixeldroid/jailang.svg]]          | /                  | /                       | [[https://repo.progsbase.com/repoviewer/][progsbase]]                   |
| [[https://github.com/kind-lang/Kind][Kind]] ([[https://github.com/kind-lang/Kind/blob/master/SYNTAX.md][Docs]])         | [[https://github.com/kind-lang/Kind][https://img.shields.io/github/last-commit/kind-lang/Kind.svg]]              | [[https://github.com/moonad/Formality#installation][INSTALL]]            | npm                     | /                           |
| [[https://www.mint-lang.com][Mint]]                | [[https://github.com/mint-lang/mint][https://img.shields.io/github/last-commit/mint-lang/mint.svg]]              | [[https://www.mint-lang.com/install][INSTALL]]            | /                       | [[https://www.mint-lang.com/packages][Packages]]                    |
| [[https://mun-lang.org/][Mun]] ([[https://docs.mun-lang.org][Docs]])          | [[https://github.com/mun-lang/mun][https://img.shields.io/github/last-commit/mun-lang/mun.svg]]                | [[https://github.com/mun-lang/mun/releases][Download]]           | /                       | /                           |
| *[[https://nim-lang.org/docs/lib.html][Nim]]*               | [[https://github.com/nim-lang/Nim][https://img.shields.io/github/last-commit/nim-lang/Nim.svg]]                | [[choosenim][choosenim]]          | [[https://github.com/nim-lang/nimble][Nimble]]                  | [[https://nim-lang.org/docs/lib.html][NimRepository]]               |
| [[https://odin-lang.org/][Odin]] ([[https://github.com/odin-lang][GitHub]])       | [[https://github.com/odin-lang/Odin][https://img.shields.io/github/last-commit/odin-lang/Odin.svg]]              | [[https://odin-lang.org/downloads/][INSTALL]]            | /                       | [[https://github.com/odin-lang/odin-libs][odin-libs]]                   |
| [[https://hundredrabbits.itch.io/orca][Orca]]                | [[https://github.com/ihundredrabbits/Orca][https://img.shields.io/github/last-commit/hundredrabbits/Orca.svg]]         | [[https://hundredrabbits.itch.io/orca][Download]]           | /                       | /                           |
| [[https://p-org.github.io/P/][P]]                   | [[https://github.com/p-org/P][https://img.shields.io/github/last-commit/p-org/P.svg]]                     | [[https://www.nuget.org/packages/P/][INSTALL]]            | /                       | [[https://www.nuget.org/packages/P/][NugetPackages]]               |
| *[[https://www.ponylang.io/][Pony]]* (‍[[https://opencollective.com/ponyc][❤]])          | [[https://github.com/ponylang/ponyc][https://img.shields.io/github/last-commit/ponylang/ponyc.svg]]              | [[https://github.com/ponylang/ponyc/blob/master/INSTALL.md][install]]/[[https://github.com/ponylang/ponyup][ponyup]]     | [[https://github.com/ponylang/corral][Corral]]/[[https://github.com/ponylang/pony-stable][pony-stable]]      | [[https://www.main.actor/][main.actor]]                  |
| [[https://www.red-lang.org/][Red ]]([[https://github.com/red/code][Example]])       | [[https://github.com/red/red][https://img.shields.io/github/last-commit/red/red.svg]]                     | [[https://www.red-lang.org/p/download.html][Download]] [[https://github.com/red/red#running-red-from-the-sources-for-contributors][Build]]     | /                       | /                           |
| [[https://rubinius.com/][Rubinius]]            | [[https://github.com/rubinius/rubinius][https://img.shields.io/github/last-commit/rubinius/rubinius.svg]]           | [[https://github.com/rubinius/rubinius#installing-rubinius][BUILD]]              | /                       | /                           |
| *[[https://www.rust-lang.org/][Rust]]*              | [[https://github.com/rust-lang/rust][https://img.shields.io/github/last-commit/rust-lang/rust.svg]]              | [[https://www.rustup.rs/][rustup]]             | [[https://github.com/rust-lang/cargo/][cargo]] (Built-in)        | [[https://crates.io/][crates.io]]                   |
| [[http://www.skiplang.com/][Skip]]                | [[https://github.com/skiplang/skip][https://img.shields.io/github/last-commit/skiplang/skip.svg]]               | [[https://github.com/skiplang/skip/blob/master/docs/developer/README-cmake.md][building]]           | /                       | /                           |
| [[https://savi.zone][Savi]]                | [[https://github.com/savi-lang/savi][https://img.shields.io/github/last-commit/savi-lang/savi.svg]]              | [[https://github.com/savi-lang/savi#try-it][INSTALL]]            | /                       | [[https://github.com/savi-lang/library-index][LibraryIndex]]                |
| [[https://www.unison-lang.org/][Unison]]              | [[https://github.com/unisonweb/unison][https://img.shields.io/github/last-commit/unisonweb/unison.svg]]            | [[https://github.com/unisonweb/unison#building-using-stack][building]]           | /                       | /                           |
| [[https://vlang.io/][V]]                   | [[https://github.com/vlang/v][https://img.shields.io/github/last-commit/vlang/v.svg]]                     |  [[https://github.com/vlang/v#installing-v-from-source][building]]          | [[https://github.com/vlang/vpm][VPM]]                | [[https://vpm.vlang.io][vpm.vlang.io]]           |
| [[https://github.com/microsoft/verona][Verona]]              | [[https://github.com/microsoft/verona][https://img.shields.io/github/last-commit/microsoft/verona.svg]]            | [[https://github.com/microsoft/verona/blob/master/docs/building.md][building]]           | /                       | /                           |
| [[https://github.com/zetzit/zz][ZetZ]]                | [[https://github.com/zetzit/zz][https://img.shields.io/github/last-commit/zetzit/zz.svg]]                   | [[https://github.com/zetzit/zz#quick-quick-start][quick-start]]        | /                       | [[https://github.com/zetzit/nursery][nursery]]                     |
| *[[https://ziglang.org/][Zig]]*               | [[https://github.com/ziglang/zig][https://img.shields.io/github/last-commit/ziglang/zig.svg]]                 | [[https://ziglang.org/download/][Download]]           | [[https://github.com/ziglang/zig/issues/943][talking..]]               | /                           |
# | *[[https://golang.org/][Go]]*            |  | [[https://github.com/travis-ci/gimme][gimme]]/[[https://github.com/moovweb/gvm][gvm]]      | [[https://github.com/golang/dep][dep]]/[[https://github.com/golang/vgo][vgo]]/[[https://github.com/niemeyer/gopkg][gopkg]]/[[https://melody.sh/docs/howto/install/][Melody]] | git/[[https://melody.sh/repo/][melodyRepo]]     |

** [[http://www-formal.stanford.edu/jmc/][CommonLisp]]

|----------------------------------+-----------------------------------------------------------------------+-----------+----------------+---------------|
| *[[https://common-lisp.net/][CommonLisp]]* ([[https://github.com/usocket/usocket][uscoket]])([[https://github.com/LispCookbook/cl-cookbook][CookBook]]) | Activity                                                              | Installer | PackageManager | PackageViewer |
|----------------------------------+-----------------------------------------------------------------------+-----------+----------------+---------------|
| [[www.sbcl.org][SBCL]]                             | [[https://github.com/sbcl/sbcl][https://img.shields.io/github/last-commit/sbcl/sbcl.svg]]               | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://github.com/clasp-developers/clasp][CLasp]]                            | [[https://github.com/clasp-developers/clasp][https://img.shields.io/github/last-commit/clasp-developers/clasp.svg]]  | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://common-lisp.net/project/ecl/][ECL]]                              | [[https://gitlab.com/embeddable-common-lisp/ecl][https://badgen.net/gitlab/last-commit/embeddable-common-lisp/ecl?.svg]] | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://abcl.org/][ABCL]]                             | [[https://github.com/armedbear/abcl][https://img.shields.io/github/last-commit/armedbear/abcl.svg]]          | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| *[[https://github.com/vygr/ChrysaLisp][ChrysaLisp]]*                     | [[https://github.com/vygr/ChrysaLisp][https://img.shields.io/github/last-commit/vygr/ChrysaLisp.svg]]         | /         | /              | /             |
| [[https://common-lisp.net/project/mkcl/][MKCL]]                             | [[https://github.com/jcbeaudoin/MKCL][https://img.shields.io/github/last-commit/jcbeaudoin/MKCL.svg]]         | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[http://www.gnu.org/software/clisp/][GNU CLISP]]                        | [[https://github.com/roswell/clisp][https://img.shields.io/github/last-commit/roswell/clisp.svg]]           | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://cmucl.org/][CMUCL]]                            | [[https://github.com/rtoy/cmucl][https://img.shields.io/github/last-commit/rtoy/cmucl.svg]]              | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://ccl.clozure.com/][Clozure CL]]                       | [[https://github.com/Clozure/ccl][https://img.shields.io/github/last-commit/Clozure/ccl.svg]]             | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://github.com/froggey/Mezzano][Mezzano]]                          | [[https://github.com/froggey/Mezzano][https://img.shields.io/github/last-commit/froggey/Mezzano.svg]]         | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://picolisp.com/wiki/?home][PicoLisp]] (*[[https://picolisp.com/wiki/?PilOS][PilOS]]*)               | [[https://github.com/picolisp/picolisp][https://img.shields.io/github/last-commit/picolisp/picolisp.svg]]       | /         | /              | /             |
| [[https://github.com/sharplispers/cormanlisp][Corman Lisp]]                      | [[https://github.com/sharplispers/cormanlisp][https://img.shields.io/github/last-commit/sharplispers/cormanlisp.svg]] | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://github.com/binghe/mcl][MCL]]                              | [[https://github.com/binghe/mcl][https://img.shields.io/github/last-commit/binghe/mcl.svg]]              | [[https://github.com/roswell/roswell][Roswell]]   | [[https://www.quicklisp.org/][Quicklisp]]/[[https://github.com/fukamachi/qlot][Qlot]] | [[http://quickdocs.org/][QuickDocs]]     |
| [[https://wikimili.com/en/Mocl][Mocl]]                             | /                                                                     | /         | /              | /             |
| *[[https://github.com/whily/yalo][YaloOS]]*                         | [[https://github.com/whily/yalo][https://img.shields.io/github/last-commit/whily/yalo.svg]]              | /         | /              | /             |
| [[https://github.com/lauryndbrown/Cisp][Cisp]]                             | [[https://github.com/lauryndbrown/Cisp][https://img.shields.io/github/last-commit/lauryndbrown/Cisp.svg]]       | /         | /              | /             |
| [[http://www.lispworks.com/][LispWorks]]                        | /                                                                     | /         | /              | /             |
| [[https://franz.com/products/allegrocl/][Allegro CL]]                       | /                                                                     | /         | /              | /             |
| [[https://wukix.com/mocl][MOCL]]                             | /                                                                     | /         | /              | /             |
| [[https://www.scieneer.com/scl/][Scieneer CL]] ([[https://lisphub.jp/doc/scl/][Doc]])                | /                                                                     | /         | /              | /             |
| [[http://smbx.org/][Symbolics Lisp Machine (Genera)]]  | /                                                                     | /         | /              | /             |

** Scheme 
|---------------------+------------------------------------------------------------------------+-----------+----------------+-----------------|
| *[[https://www.scheme.com/tspl4/][Scheme]]*            | Activity                                                               | Installer | PackageManager | PackageViewer   |
|---------------------+------------------------------------------------------------------------+-----------+----------------+-----------------|
| [[https://gitlab.com/owl-lisp/owl][Owl Lisp]]            | [[https://gitlab.com/owl-lisp/owl][https://badgen.net/gitlab/last-commit/owl-lisp/owl?.svg]]                | /         | /              | /               |
| [[http://www-sop.inria.fr/mimosa/fp/Bigloo/][Bigloo]]              | [[https://github.com/manuel-serrano/bigloo][https://img.shields.io/github/last-commit/manuel-serrano/bigloo.svg]]    | /         | /              | /               |
| *[[https://github.com/cisco/ChezScheme][Cisco Chez]]*        | [[https://github.com/cisco/ChezScheme][https://img.shields.io/github/last-commit/cisco/ChezScheme.svg]]         | [[https://github.com/cisco/ChezScheme/blob/master/BUILDING][building]]  | [[https://akkuscm.org/][AKKU]] [[https://github.com/guenchi/Raven][Raven]]     | [[https://akkuscm.org/packages/][Packages]] [[http://ravensc.com/list][list]]   |
| *[[https://github.com/racket/ChezScheme][Racket Chez]]*       | [[https://github.com/racket/ChezScheme][https://img.shields.io/github/last-commit/racket/ChezScheme.svg]]        | [[https://github.com/cisco/ChezScheme/blob/master/BUILDING][building]]  | [[https://akkuscm.org/][AKKU]] [[https://github.com/guenchi/Raven][Raven]]     | [[https://akkuscm.org/packages/][Packages]] [[http://ravensc.com/list][list]]   |
| *[[http://racket-lang.org/][Racket]]*            | [[https://github.com/racket/racket][https://img.shields.io/github/last-commit/racket/racket.svg]]            | [[http://download.racket-lang.org/][Download]]  | [[https://docs.racket-lang.org/raco/][raco]]           | [[http://pkgs.racket-lang.org/][Racket Packages]] |
| [[https://www.gnu.org/software/mit-scheme/][MIT Scheme]] ([[http://groups.csail.mit.edu/mac/projects/scheme/][groups]]) | [[https://github.com/barak/mit-scheme][https://img.shields.io/github/last-commit/barak/mit-scheme.svg]]         | [[https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/][Download]]  | [[https://akkuscm.org/][AKKU]] [[https://github.com/guenchi/Raven][Raven]]     | [[https://akkuscm.org/packages/][Packages]] [[http://ravensc.com/list][list]]   |
| [[https://justinethier.github.io/cyclone/][Cyclone]]             | [[https://github.com/justinethier/cyclone][https://img.shields.io/github/last-commit/justinethier/cyclone.svg]]     | [[https://justinethier.github.io/cyclone/docs/User-Manual#installation][INSTALL]]   | [[https://github.com/cyclone-scheme/winds][winds]]          | [[https://justinethier.github.io/cyclone/docs/API.html#srfi-libraries][Libraries]]       |
| [[https://ryansuchocki.github.io/microscheme/][MicroScheme]]         | [[https://github.com/ryansuchocki/microscheme][https://img.shields.io/github/last-commit/ryansuchocki/microscheme.svg]] | [[https://ryansuchocki.github.io/microscheme/download][Download]]  | /              | /               |
| [[https://www.gnu.org/software/guile/][GNU Guile]]           | [[https://github.com/texmacs/guile][https://img.shields.io/github/last-commit/texmacs/guile.svg]]            | [[https://www.gnu.org/software/guile/download/][Download]]  | [[https://akkuscm.org/][AKKU]] [[https://github.com/guenchi/Raven][Raven]]     | [[https://akkuscm.org/packages/][Packages]] [[http://ravensc.com/list][list]]   |

** Clojure Like
|------------------------------+----------------------------------------------------------------------+------------------+----------------+------------------|
| *Clojure Like* ([[https://github.com/bbatsov/clojure-style-guide][STYLE]] [[https://nrepl.org/nrepl/index.html][nREPL]]) | Activity                                                             | Installer        | PackageManager | PackageViewer    |
|------------------------------+----------------------------------------------------------------------+------------------+----------------+------------------|
| *[[https://clojure.org/][Clojure]]* ([[https://clojuredocs.org/][Docs]]) ([[https://github.com/clojure-link/link][link]])      | [[https://github.com/clojure/clojure][https://img.shields.io/github/last-commit/clojure/clojure.svg]]        | [[https://sdkman.io/sdks#leiningen][SDKMAN]]           | [[https://leiningen.org/][Leiningen]]/[[https://github.com/boot-clj/boot][Boot]] | [[https://clojars.org/][clojars]]          |
| [[https://github.com/clojure/clojure-clr][Clojure-CLR]]                  | [[https://github.com/clojure/clojure-clr][https://img.shields.io/github/last-commit/clojure/clojure-clr.svg]]    | [[https://github.com/clojure/clojure-clr/wiki/Getting-started#installing-clojureclr-as-a-dotnet-tool][INSTALL]]          |                |                  |
| [[https://clojurescript.org/][ClojureScript]]                | [[https://github.com/clojure/clojurescript][https://img.shields.io/github/last-commit/clojure/clojurescript.svg]]  | [[https://github.com/thheller/shadow-cljs][shadow-cljs]]/[[https://github.com/anmonteiro/lumo][lumo]] | npm/yarn       | [[http://cljsjs.github.io/][CLJSJS]]           |
| [[https://github.com/borkdude/sci][Small Clojure Interpreter]]    | [[https://github.com/borkdude/sci][https://img.shields.io/github/last-commit/borkdude/sci.svg]]           | [[https://github.com/borkdude/sci#installation][INSTALL]]          | /              | /                |
| [[https://github.com/babashka/babashka][Babashka]]                     | [[https://github.com/babashka/babashka][https://img.shields.io/github/last-commit/babashka/babashka.svg]]      |                  |                |                  |
| [[https://github.com/LuxLang/lux][Lux]]                          | [[https://github.com/LuxLang/lux][https://img.shields.io/github/last-commit/LuxLang/lux.svg]]            |                  |                |                  |
| *[[https://janet-lang.org/][Janet]]*                      | [[https://github.com/janet-lang/janet][https://img.shields.io/github/last-commit/janet-lang/janet.svg]]       | [[https://janet-lang.org/introduction.html][INSTALL]]          | [[https://janet-lang.org/index.html][jpm]] (Built-in) | [[https://github.com/janet-lang/pkgs/blob/master/pkgs.janet][pkgs.janet]]       |
| [[https://phel-lang.org/][Phel]]                         | [[https://github.com/phel-lang/phel-lang][https://img.shields.io/github/last-commit/phel-lang/phel-lang.svg]]    | [[https://phel-lang.org/documentation/getting-started/][INSTALL]]          | [[https://getcomposer.org/][Composer]]       | [[https://packagist.org/][Packagist]]        |
| [[https://github.com/carp-lang/Carp][Carp]] ([[https://github.com/carp-lang/Carp/blob/master/docs/LanguageGuide.md][Guide]])                 | [[https://github.com/carp-lang/Carp][https://img.shields.io/github/last-commit/carp-lang/Carp.svg]]         | [[Https://github.com/carp-lang/Carp/blob/master/docs/Install.md][INSTALL]]          | [[https://github.com/carpentry-org][Carpentry]]      | [[https://github.com/carp-lang/Carp/blob/master/docs/Libraries.md#core-modules][Core]] /[[https://github.com/carpentry-org][ Carpentry]] |
| [[hylang.org][Hy]] ([[https://github.com/allison-casey/HyREPL][HyREPL]])                  | [[https://github.com/hylang/hy][https://img.shields.io/github/last-commit/hylang/hy.svg]]              | [[https://pypi.org/project/pip/][pip]]              | [[https://pypi.org/project/pip/][pip]]            | [[https://pypi.org][PyPI]]             |
| [[https://joker-lang.org/][Joker]]                        | [[https://github.com/candid82/joker][https://img.shields.io/github/last-commit/candid82/joker.svg]]         | [[https://joker-lang.org/][INSTALL]]          |                |                  |
| [[https://github.com/nasser/magic][MAGIC]]                        | [[https://github.com/nasser/magic][https://img.shields.io/github/last-commit/nasser/magic.svg]]           | [[https://github.com/nasser/magic#getting-started][building]]         | [[https://github.com/nasser/nostrand][Nostrand]]       | /                |
| [[https://github.com/borkdude/deps.clj][deps.clj]]                     | [[https://github.com/borkdude/deps.clj][https://img.shields.io/github/last-commit/borkdude/deps.clj.svg]]      |                  |                |                  |
| *[[https://github.com/eshrh/matsurika][Matsurika]]* (jannet fork)    | [[https://github.com/eshrh/matsurika][https://img.shields.io/github/last-commit/eshrh/matsurika.svg]]        | [[https://github.com/eshrh/matsurika][BUILD]]            | /              | /                |
| [[https://github.com/bfontaine/clj][clj]]                          | [[https://github.com/bfontaine/clj][https://img.shields.io/github/last-commit/bfontaine/clj.svg]]          | [[https://github.com/bfontaine/clj#install][INSTALL]]          | pip            | /                |
| [[https://github.com/dirkschumacher/llr][llr]]                          | [[https://github.com/dirkschumacher/llr][https://img.shields.io/github/last-commit/dirkschumacher/llr.svg]]     | [[https://github.com/dirkschumacher/llr#installation][INSTALL]]          | /              | /                |
| [[https://maxinteger.github.io/pocket-lisp-page/][Pocket lisp]]                  | [[https://github.com/maxinteger/pocket-lisp][https://img.shields.io/github/last-commit/maxinteger/pocket-lisp.svg]] | [[https://github.com/maxinteger/pocket-lisp#for-contributors][INSTALL]]          | /              | /                |
| [[https://github.com/clojerl/clojerl][Clojerl]]                      | [[https://github.com/clojerl/clojerl][https://img.shields.io/github/last-commit/clojerl/clojerl.svg]]        | [[https://github.com/clojerl/clojerl][building]]         |                |                  |
| [[https://github.com/clojure-rs/ClojureRS][ClojureRS]]                    | [[https://github.com/clojure-rs/ClojureRS][https://img.shields.io/github/last-commit/clojure-rs/ClojureRS.svg]]   |                  |                |                  |
| [[https://github.com/lsevero/abclj][ArmedBearClojure]]             | [[https://github.com/lsevero/abclj][https://img.shields.io/github/last-commit/lsevero/abclj.svg]]          |                  |                |                  |
| [[https://github.com/Toccata-Lang/toccata][Toccata]]                      | [[https://github.com/Toccata-Lang/toccata][https://img.shields.io/github/last-commit/Toccata-Lang/toccata.svg]]   |                  |                |                  |
| [[https://github.com/apricot-lang/apricot][Apricot]]                      | [[https://github.com/apricot-lang/apricot][https://img.shields.io/github/last-commit/apricot-lang/apricot.svg]]   | [[https://github.com/apricot-lang/apricot#install][INSTALL]]          | /              | /                |
| [[https://github.com/alandipert/gherkin][gherkin]]                      | [[https://github.com/alandipert/gherkin][https://img.shields.io/github/last-commit/alandipert/gherkin.svg]]     | [[https://github.com/alandipert/gherkin][git clone]]        | /              | /                |
| [[https://arcadia-unity.github.io/][Arcadia]]                      | [[https://github.com/arcadia-unity/Arcadia][https://img.shields.io/github/last-commit/arcadia-unity/Arcadia.svg]]  |                  |                |                  |
| [[https://github.com/dundalek/closh][Closh]]                        | [[https://github.com/dundalek/closh][https://img.shields.io/github/last-commit/dundalek/closh.svg]]         |                  |                |                  |
| [[https://github.com/ruricolist/cloture][Cloture]]                      | [[https://github.com/ruricolist/cloture][https://img.shields.io/github/last-commit/ruricolist/cloture.svg]]     |                  |                |                  |
| [[https://github.com/incanter/incanter][Incanter]]                     | [[https://github.com/incanter/incanter][https://img.shields.io/github/last-commit/incanter/incanter.svg]]      | [[https://github.com/incanter/incanter#building-incanter][building]]         | /              | /                |
| [[https://github.com/timothypratley/rustly][Rustly]]                       | [[https://github.com/timothypratley/rustly][https://img.shields.io/github/last-commit/timothypratley/rustly.svg]]  |                  |                |                  |
| [[https://ferret-lang.org/][Ferret]]                       | [[https://github.com/nakkaya/ferret][https://img.shields.io/github/last-commit/nakkaya/ferret.svg]]         | lein             |                |                  |
| [[https://github.com/joinr/clclojure][CLClojure]]                    | [[https://github.com/joinr/clclojure][https://img.shields.io/github/last-commit/joinr/clclojure.svg]]        |                  |                |                  |
| [[https://github.com/Gozala/wisp][Wisp]]                         | [[https://github.com/wisp-lang/wisp][https://img.shields.io/github/last-commit/wisp-lang/wisp.svg]]         | npm              | npm/yarn       | /                |
| [[https://github.com/pixie-lang/pixie][Pixie]]                        | [[https://github.com/pixie-lang/pixie][https://img.shields.io/github/last-commit/pixie-lang/pixie.svg]]       | [[https://github.com/pixie-lang/pixie#building][building]]         | /              | /                |
| [[https://github.com/bailesofhey/slisp][SLisp]]                        | [[https://github.com/bailesofhey/slisp][https://img.shields.io/github/last-commit/bailesofhey/slisp.svg]]      | /                | /              | /                |
| [[http://ki-lang.org/][ki]]                           | [[https://github.com/lantiga/ki][https://img.shields.io/github/last-commit/lantiga/ki.svg]]             | [[http://ki-lang.org/][INSTALL]]          | npm/yarn       | /                |
| [[https://github.com/7even/carbonate][Carbonate]]                    | [[https://github.com/7even/carbonate][https://img.shields.io/github/last-commit/7even/carbonate.svg]]        | [[https://github.com/7even/carbonate#installation][INSTALL]]          | /              | /                |
| [[https://github.com/artagnon/rhine-ml][Rhine]]                        | [[https://github.com/artagnon/rhine-ml][https://img.shields.io/github/last-commit/artagnon/rhine-ml.svg]]      | [[https://github.com/artagnon/rhine-ml#building][building]]         | /              | /                |
| [[https://github.com/tpope/timl][TimL]]                         | [[https://github.com/tpope/timl][https://img.shields.io/github/last-commit/tpope/timl.svg]]             | [[https://github.com/tpope/timl#getting-started][INSTALL]]          | /              | /                |

** Lisp-1
|---------------+--------------------------------------------------------------------------+-----------+----------------+-----------------|
| *LISP-1*      | Activity                                                                 | Installer | PackageManager | PackageViewer   |
|---------------+--------------------------------------------------------------------------+-----------+----------------+-----------------|
| [[https://arclanguage.github.io/][Arc]]           | [[https://github.com/arclanguage/anarki][https://img.shields.io/github/last-commit/arclanguage/anarki.svg]]         | [[https://arclanguage.github.io/][INSTALL]]   | /              | /               |
| [[https://shenlanguage.org/index.html][Shen]]          | [[https://github.com/Shen-Language/shen-sources][https://img.shields.io/github/last-commit/Shen-Language/shen-sources.svg]] | [[https://shenlanguage.org/download.html][Download]]  | /              | /               |
| [[https://www.cliki.net/Qi][Qi]] ([[https://github.com/countvajhula/qi-tutorial][tutorial]]) | /                                                                        | /         | /              | /               |
| [[http://www.newlisp.org/][newLISP]]       | /                                                                        | [[http://www.newlisp.org/index.cgi?Downloads][Download]]  | /              | [[http://www.newlisp.org/modules/][Modules]]         |
| *[[http://racket-lang.org/][Racket]]*      | [[https://github.com/racket/racket][https://img.shields.io/github/last-commit/racket/racket.svg]]              | [[http://download.racket-lang.org/][Download]]  | [[https://docs.racket-lang.org/raco/][raco]]           | [[http://pkgs.racket-lang.org/][Racket Packages]] |
| [[https://gamelisp.rs/][GameLisp]]      | [[https://github.com/fleabitdev/glsp/][https://img.shields.io/github/last-commit/fleabitdev/glsp.svg]]            | [[https://crates.io/crates/glsp/][crate]]     | /              | /               |
| [[http://joxa.org/][Joxa]]          | [[https://github.com/joxa/joxa][https://img.shields.io/github/last-commit/joxa/joxa.svg]]                  | [[http://joxa.org/#Installation][INSTALL]]   | /              | /               |
| [[https://gamelisp.rs/][GameLisp]]      | [[https://github.com/fleabitdev/glsp/][https://img.shields.io/github/last-commit/fleabitdev/glsp.svg]]            | [[https://crates.io/crates/glsp/][crate]]     | /              | /               |

** Lisp-2
|----------+-------------------------------------------------------+-----------+----------------+---------------|
| *LISP-2* |                                                       | Installer | PackageManager | PackageViewer |
|----------+-------------------------------------------------------+-----------+----------------+---------------|
| [[https://lfe.io/][LFE]]      | [[https://github.com/lfe/lfe][https://img.shields.io/github/last-commit/lfe/lfe.svg]] |           |                |               |

** Editor
| Name          | Activity                                                                  | Installer    | PackageManager       | Repository             |
|---------------+---------------------------------------------------------------------------+--------------+----------------------+------------------------|
| [[https://atom.io/][Atom]]          | [[https://github.com/atom/atom][https://img.shields.io/github/last-commit/atom/atom.svg]]                   | [[https://atom.io/][Download]]     | [[https://github.com/atom/apm][apm]](Built-in)/[[https://atmospherejs.com/][Meteor]] | [[https://atom.io/packages][Atom]] / [[https://atmospherejs.com/][Meteor]]          |
| [[http://brackets.io/][Brackets]]      | [[https://github.com/adobe/brackets][https://img.shields.io/github/last-commit/adobe/brackets.svg]]              | [[https://github.com/adobe/brackets/releases][Download]]     | Built-in             | [[https://registry.brackets.io/][Registry]]               |
| [[https://github.com/CodeEditApp/CodeEdit][CodeEdit]]      | [[https://github.com/CodeEditApp/CodeEdit][https://img.shields.io/github/last-commit/CodeEditApp/CodeEdit.svg]]        | [[https://github.com/CodeEditApp/CodeEdit][BUILD]]        | /                    | /                      |
| [[http://www.uvviewsoft.com/cudatext/][CudaText]]      | [[https://github.com/Alexey-T/CudaText][https://img.shields.io/github/last-commit/Alexey-T/CudaText.svg]]           | [[http://www.uvviewsoft.com/cudatext/download.html][Download]]     | Build-in             | [[https://sourceforge.net/p/synwrite/wiki/Lexers%20list/][Lexers]]                 |
| [[https://eclipse.org/][Eclipse]]       | [[https://github.com/eclipse/eclipse-collections][https://img.shields.io/github/last-commit/eclipse/eclipse-collections.svg]] | [[https://www.eclipse.org/downloads/][Download]]     | Built-in             | [[https://marketplace.eclipse.org/][Marketplace]]            |
| *[[https://www.gnu.org/software/emacs/][Emacs]]*       | [[https://github.com/emacs-mirror/emacs][https://img.shields.io/github/last-commit/emacs-mirror/emacs.svg]]          | [[https://www.gnu.org/software/emacs/][Download]]     | Built-in / [[https://github.com/cask/cask][Cask]]      | [[https://melpa.org/#/][MELPA]]                  |
| [[https://www.jetbrains.com/][JetBrains-IDE]] | /                                                                         | [[https://www.jetbrains.com/][Download]]     | Built-in             | [[https://plugins.jetbrains.com/][PluginsRepository]]      |
| [[http://kakoune.org/][Kakoune]]       | [[https://github.com/mawww/kakoune][https://img.shields.io/github/last-commit/mawww/kakoune.svg]]               | [[https://github.com/mawww/kakoune/releases][Download]]     | Built-in             | [[https://github.com/search?q=topic%3Akakoune+topic%3Aplugin][Plugins]]                |
| [[http://lighttable.com/][LightTable]]    | [[https://github.com/LightTable/LightTable][https://img.shields.io/github/last-commit/LightTable/LightTable.svg]]       | [[http://lighttable.com/#][Download]]     | Built-in             | [[https://github.com/LightTable/plugin-metadata][Plugin-Metadata]]        |
| [[https://micro-editor.github.io/index.html][MicroEditor]]   | [[https://github.com/zyedidia/micro][https://img.shields.io/github/last-commit/zyedidia/micro.svg]]              | [[https://micro-editor.github.io/index.html][Download]] [[https://github.com/zyedidia/micro#building-from-source][src]] | micro (Built-in)     | [[https://micro-editor.github.io/plugins.html][Plugins]]                |
| [[http://aquest.com/emacs.htm][MicroEmacs]]    | [[https://github.com/ipstone/microemacs][https://img.shields.io/github/last-commit/ipstone/microemacs.svg]]          | [[http://aquest.com/downloads/emacs5.zip][src]]          | /                    | /                      |
| *[[http://www.mclide.com/][MCLIDE]]*      | [[https://github.com/njordhov/mclide][https://img.shields.io/github/last-commit/njordhov/mclide.svg]]             | [[http://www.mclide.com/][Download]]     | /                    | /                      |
| [[https://github.com/DexterLagan/newIDE][newIDE]]        | [[https://github.com/DexterLagan/newIDE][https://img.shields.io/github/last-commit/DexterLagan/newIDE.svg]]          |              |                      |                        |
| [[https://www.nano-editor.org/][Nano]]          | [[https://github.com/madnight/nano][https://img.shields.io/github/last-commit/madnight/nano.svg]]               | [[https://www.nano-editor.org/download.php][src]] [[https://git.savannah.gnu.org/cgit/nano.git/][git]]      | /                    | [[https://github.com/serialhex/nano-highlight][nano-highlight]]         |
| *[[https://neovim.io/][Neovim]]*      | [[https://github.com/neovim/neovim][https://img.shields.io/github/last-commit/neovim/neovim.svg]]               | [[https://github.com/neovim/neovim/wiki/Installing-Neovim][Install]]  [[https://github.com/neovim/neovim][src]] | [[https://github.com/junegunn/vim-plug][vim-plug]]             | [[https://vim.sourceforge.io/search.php][Search-for-Vim-Script]]  |
| *[[https://v2.onivim.io/][OniVim]]*      | [[https://github.com/onivim/oni2][https://img.shields.io/github/last-commit/onivim/oni2.svg]]                 | [[https://onivim.github.io/docs/getting-started/installation][Install]]      | /                    | [[https://open-vsx.org/][Open-VSX-Registry]]      |
| [[https://www.sublimetext.com/][Sublime]]       | [[https://github.com/SublimeText/PackageDev][https://img.shields.io/github/last-commit/SublimeText/PackageDev.svg]]      | [[https://www.sublimetext.com/3][Download]]     | [[https://packagecontrol.io/][PackageControl]]       | [[https://packagecontrol.io/][PackageControlPackages]] |
| [[https://www.texmacs.org/tmweb/home/welcome.en.html][TeXmacs]]       | [[https://github.com/texmacs/texmacs][https://img.shields.io/github/last-commit/texmacs/texmacs.svg]]             | [[https://www.texmacs.org/tmweb/download/linux.en.html][Download]]     | /                    | [[https://github.com/texmacs/plugins][Plugins]]                |
| [[https://macromates.com/][TextMate]]      | [[https://github.com/textmate/textmate][https://img.shields.io/github/last-commit/textmate/textmate.svg]]           | [[http://macromates.com/download][Download]] [[https://github.com/textmate/textmate][src]] | Built-in             | [[https://macromates.com/textmate/manual/snippets][Snippets]]               |
| [[https://git.kernel.org/pub/scm/editors/uemacs/uemacs.git][uemacs]]        | [[https://github.com/torvalds/uemacs][https://img.shields.io/github/last-commit/torvalds/uemacs.svg]]             | [[https://github.com/torvalds/uemacs][src]]          | /                    | /                      |
| [[https://code.visualstudio.com/][VSCode]]        | [[https://github.com/Microsoft/vscode][https://img.shields.io/github/last-commit/Microsoft/vscode.svg]]            | [[https://code.visualstudio.com/Download][Download]]     | Built-in             | [[https://marketplace.visualstudio.com/VSCode][Marketplace]]            |
| [[https://www.visualstudio.com/downloads/][VisualStudio]]  | /                                                                         | [[https://www.visualstudio.com/downloads/][Download]]     | Built-in             | [[https://marketplace.visualstudio.com/vs][Marketplace]]            |
| *[[http://www.vim.org/][Vim]]*         | [[https://github.com/vim/vim][https://img.shields.io/github/last-commit/vim/vim.svg]]                     | [[https://vim.sourceforge.io/download.php][Download]]     | [[https://github.com/VundleVim/Vundle.Vim][Vundle.vim]] [[https://github.com/junegunn/vim-plug][vim-plug]]  | [[https://vim.sourceforge.io/search.php][Search-for-Vim-Script]]  |
| [[https://github.com/xi-editor/xi-editor][XiEditor]]      | [[https://github.com/xi-editor/xi-editor][https://img.shields.io/github/last-commit/xi-editor/xi-editor.svg]]         | [[https://github.com/xi-editor/xi-editor#frontends][Frontends]]    | /                    | /                      |
| [[https://developer.apple.com/xcode/][Xcode]]         | /                                                                         | [[https://developer.apple.com/xcode/][Download]]     | [[https://github.com/alcatraz/Alcatraz][Alcatraz]]             | [[https://github.com/alcatraz/alcatraz-packages][AlcatrazPackages]]       |
| [[https://zed.dev/][Zed]]           | [[https://github.com/zed-industries/feedback][https://img.shields.io/github/last-commit/zed-industries/feedback.svg]]     | /            | /                    | /                      |

** OS
| Name            | Installer | PackageManager    | Repository          |
|-----------------+-----------+-------------------+---------------------|
| [[https://www.android.com/][Android]]         | [[https://source.android.com/setup/downloading][Download]]  | None              | [[https://play.google.com/store][GooglePlay]]          |
| [[https://www.chromium.org/chromium-os][ChromeOS]]        | [[https://www.chromium.org/chromium-os][Download]]  | [[https://github.com/skycocker/chromebrew][chromebrew]]        | [[https://github.com/skycocker/chromebrew/tree/master/packages][packages]]            |
| cross-platform  | /         | [[https://gofi.sh/#install][GoFish]]            | /                   |
| Cluster         | None      | [[https://saltstack.com/][SlatStack]]         | [[https://repo.saltstack.com/][PackageRepo]]         |
| [[https://www.cygwin.com/][Cygwin]]          | [[https://cygwin.com/install.html][Download]]  | [[https://github.com/kou1okada/apt-cyg][apt-cyg]]/[[https://github.com/svnpenn/sage][sage]]      | [[https://cygwin.com/cgi-bin2/package-grep.cgi][CygwinPackageSearch]] |
| *[[https://www.docker.com][Docker]]*        | [[https://www.docker.com/get-docker][Download]]  | [[https://hub.docker.com/][docker]](Built-in)  | [[https://hub.docker.com/][DockerHub]]           |
| [[https://www.gnu.org/software/guix/][GNU Guix]]        | [[https://www.gnu.org/software/guix/download/][Download]]  | Guix (Built-in)   | [[https://www.gnu.org/software/guix/packages/][Packages]]            |
| [[https://kubernetes.io/][Kubernetes]]      | [[https://kubernetes.io/docs/tasks/tools/install-kubectl/][Install]]   | [[https://helm.sh/][Helm]]              | [[https://hub.docker.com/][DockerHub]]           |
| [[https://www.kernel.org/][Linux]]           | [[https://www.kernel.org/][Download]]  | [[http://linuxbrew.sh/][Linuxbrew]]         | [[http://braumeister.org/][Formulae]]            |
| [[https://www.tecmint.com/best-linux-desktop-environments/][LinuxDesktop]]    | /         | [[https://snapcraft.io/][SnapCraft]]         | [[https://snapcraft.io/store][Store]]               |
| [[https://developer.apple.com/macos/][macOS]]           | [[https://brew.sh/][Install]]   | [[https://brew.sh/][Homebrew]]          | [[http://formulae.brew.sh/][Formulae]]            |
| [[http://www.msys2.org/][MSYS2]]           | [[http://www.msys2.org/][Download]]  | pacman(Built-in)  | [[https://packages.msys2.org/search][MSYS2-packages]]      |
| [[https://nixos.org/][NixOS]]           | [[https://nixos.org/nixos/download.html][Download]]  | [[https://nixos.org/nix/][Nix]]               | [[https://nixos.org/nixpkgs/][NixPackages]]         |
| [[http://node-os.com/][NodeOS]]          | [[https://github.com/NodeOS/NodeOS/releases][Download]]  | NPM(Built-in)     | [[https://www.npmjs.com/][NPMRepository]]       |
| [[http://www.ros.org/][ROS]]             | [[http://www.ros.org/][Download]]  | [[http://wiki.ros.org/rosdep][rosdep]]            | [[http://www.ros.org/browse/list.php][ROS-Repository]]      |
| [[https://solus-project.com/][Solus]]           | [[https://solus-project.com/download/][Download]]  | [[https://solus-project.com/articles/package-management/repo-management/en/][eopkg]](Built-in)   | [[https://packages.solus-project.com/][Packages]]            |
| [[https://improbable.io/games][SpatialOS]]       | [[https://improbable.io/get-spatialos][Download]]  | [[https://docs.improbable.io/reference/12.1/shared/spatial-cli/introduction][spatial]](Built-in) | None                |
| [[https://www.microsoft.com/en-us/windows/][Windows]] ([[https://chocolatey.org/][Choco]]) | [[https://chocolatey.org/install][Install]]  | [[https://chocolatey.org/][Chocolatey]]        | [[https://chocolatey.org/packages][ChocolateyPackages]]  |
| [[https://www.microsoft.com/en-us/windows/][Windows]] ([[https://scoop.sh/][Scoop]]) | [[https://scoop.sh/][Install]]   | [[https://scoop.sh/][scoop]]             | [[https://github.com/lukesampson/scoop/tree/master/bucket][ScoopBucket]]         |
| [[https://www.microsoft.com/en-us/windows/][Windows]] ([[https://learn.microsoft.com/en-us/windows/package-manager/][Windows Package Manager]]) | [[https://github.com/microsoft/winget-cli#installing-the-client][Install]]   | [[https://github.com/microsoft/winget-cli][winget-cli]]             | [[https://github.com/microsoft/winget-pkgs][winget-pkgs]] ([[https://winget.run/][winget.run]])        |
| [[https://github.com/epitron/upm#package-tools-to-wrap][Universal]]       | /         | [[https://github.com/epitron/upm][upm]]               | None                |

** Other
| Name          | Installer | PackageManager    | Repository  |
|---------------+-----------+-------------------+-------------|
| *[[https://tiswww.case.edu/php/chet/bash/bashtop.html][Bash-it]]*     | [[https://github.com/Bash-it/bash-it][Install]]   | bash-it           | [[https://github.com/Bash-it/bash-it/wiki/Themes][Themes]]      |
| *[[http://www.zsh.org/][Oh-my-zsh]]*   | [[https://github.com/robbyrussell/oh-my-zsh][Install]]   | [[http://antigen.sharats.me/][Antigen]]           | [[https://github.com/unixorn/awesome-zsh-plugins#plugins][Plugins]]     |
| IoT           | None      | [[http://platformio.org/][PlatformaIO]]       | [[http://platformio.org/lib][Libraries]]   |
| [[https://github.com/kdeldycke/meta-package-manager][Meta Package Manager]]       | [[https://kdeldycke.github.io/meta-package-manager/install.html][Install]]       | A lot | None        |
| [[https://nanobox.io/][Nanobox]]       | [[https://nanobox.io/pricing/][Buy]]       | nanobox(Built-in) | None        |
| [[https://puppet.com/][Puppet]]        | [[https://puppet.com/download-puppet-enterprise][Download]]  | [[https://forge.puppet.com/][Forge]](Built-in)   | [[https://forge.puppet.com/][PuppetForge]] |
| [[http://reaper.fm/index.php][REAPER]]        | [[http://reaper.fm/download.php][Download]]  | [[https://github.com/cfillion/reapack][Reapack]]           | [[https://reapack.com/repos][Repos]]       |
| [[https://coreos.com/rkt/][Rocket(rkt)]]   | [[https://github.com/rkt/rkt][Download]]  | rkt(Built-in)     | [[https://hub.docker.com/][Docker Hub]]  |
| [[https://unity3d.com/][Unity3D]]       | [[https://forum.unity.com/threads/unity-hub-release-candidate-0-20-1-is-now-available.546315/][UnityHub]]  | [[https://github.com/modesttree/projeny][Projeny]]           | [[https://www.assetstore.unity3d.com/][Asset Store]] |
| [[https://wordpress.org/][WordPress]]     | [[https://wordpress.org/download/][Download]]  | Built-in          | [[https://libraries.io/wordpress][Plugins]]     |
| Web ([[https://parceljs.org/getting_started.html][Parcel]])  | [[https://parceljs.org/getting_started.html][yarn/npm]]  | [[https://parceljs.org/getting_started.html][parcel]]            | None        |
| Web ([[https://webpack.js.org/guides/installation/][webpack]]) | [[https://webpack.js.org/guides/installation/][npm]]       | [[https://webpack.js.org/guides/installation/][webpack]]           | None        |
